apiVersion: v1
kind: Service
metadata:
  name: ingress-controller
  namespace: default  # You can change the namespace as needed
spec:
  type: LoadBalancer
  selector:
    app: ingress-controller
  ports:
    - name: http
      port: 80
      targetPort: 80
    - name: https
      port: 443
      targetPort: 443