apiVersion: v1

kind: Service

metadata:
  name: media-service
  labels:
    app: media-service
spec:
  type: NodePort
  ports:
    - port: 8200
      targetPort: 8200
      protocol: TCP
  selector:
    app: media-service