apiVersion: v1

kind: Service

metadata:
  name: security-service
  labels:
    app: security-service
spec:
  type: LoadBalancer
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
  selector:
    app: security-service