apiVersion: v1

kind: Service

metadata:
  name: postgres-chat-service
  labels:
    app: postgres-chat-service
spec:
  type: NodePort
  ports:
    - port: 5432
      targetPort: 5432
      nodePort: 30001
  selector:
    app: postgres-chat-service