apiVersion: v1

kind: PersistentVolume
metadata:
  name: postgres-chat-service-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/database-data/chat-service"