apiVersion: v1

kind: PersistentVolumeClaim

metadata:
    name: postgres-chat-service-claim
spec:
    storageClassName: manual
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 8Gi