apiVersion: v1

kind: Service

metadata:
  name: user-management
  labels:
    app: user-management
spec:
  # to specify, whenever we hit the endpoint, we will be using the load balancer
  # to distribute the load to the pods
  type: LoadBalancer
  ports:
    - port: 8040
      targetPort: 8040
      protocol: TCP
  selector:
    app: user-management